package com.example.mentormatch.enum

enum class SoftSkill {
    COMUNICACAO,
    TRABALHO_EM_EQUIPE,
    RESOLUCAO_DE_PROBLEMAS,
    ADAPTABILIDADE,
    GESTAO_DO_TEMPO,
    LIDERANCA,
    PENSAMENTO_CRITICO,
    CRIATIVIDADE,
    EMPATIA,
    COLABORACAO,
    RESILIENCIA,
    INTELIGENCIA_EMOCIONAL
}